# Generated by Django 3.0.6 on 2020-07-09 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.TextField(max_length=30)),
                ('doc_type', models.TextField(max_length=8)),
                ('order_num_doc', models.TextField(max_length=15)),
                ('associated_doc_type', models.TextField(max_length=8)),
                ('order_num_associated_doc', models.TextField(max_length=15)),
                ('date_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('pdf_file_path', models.FileField(default=None, upload_to='pdfs_encomendas')),
                ('parts_string', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField(max_length=10)),
                ('name', models.TextField(max_length=30)),
                ('stock_quantity', models.TextField(max_length=6)),
                ('stock_unit', models.TextField(max_length=2)),
                ('material', models.TextField(max_length=30)),
                ('sector', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.TextField(max_length=30)),
                ('doc_type', models.TextField(max_length=8)),
                ('num_doc', models.TextField(max_length=15)),
                ('associated_doc_type', models.TextField(max_length=8)),
                ('order_num_associated_doc', models.TextField(max_length=15)),
                ('date_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
