# Generated by Django 3.0.6 on 2020-07-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_organizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='date_inserted',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='part',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='user',
        ),
        migrations.AddField(
            model_name='part',
            name='storage',
            field=models.TextField(default='4', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='technical_PDF',
            field=models.FileField(default=None, upload_to='fichas_técnicas_artigos'),
        ),
        migrations.AddField(
            model_name='part',
            name='weight',
            field=models.TextField(default='0', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='parts_string',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
