# Generated by Django 3.0.6 on 2020-07-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_organizer', '0002_auto_20200710_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='stock_unit',
            field=models.TextField(max_length=3),
        ),
    ]
