# Generated by Django 3.0.6 on 2020-07-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_organizer', '0003_auto_20200710_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.TextField(max_length=130),
        ),
        migrations.AlterField(
            model_name='part',
            name='reference',
            field=models.TextField(max_length=12),
        ),
        migrations.AlterField(
            model_name='part',
            name='stock_quantity',
            field=models.TextField(max_length=8),
        ),
    ]
