# Generated by Django 3.0.6 on 2020-07-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_organizer', '0004_auto_20200716_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='car_info',
            field=models.TextField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='total_weight',
            field=models.TextField(default='0', max_length=15),
            preserve_default=False,
        ),
    ]
