# Generated by Django 3.0.6 on 2020-07-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_organizer', '0005_auto_20200716_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='car_info',
            new_name='vehicle_info',
        ),
    ]
