# Generated by Django 3.0.6 on 2020-07-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_organizer', '0006_auto_20200726_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
