# Generated by Django 3.0.6 on 2020-08-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_organizer', '0007_shipping_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='date',
            new_name='date_inserted',
        ),
    ]
